### ISSUE TITLE
Boot directly into last opened project or into a new project

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#120]
Would need to have a persistent setting that stores the currently open project.

Also because of potentially long time it takes to load larger samples from sdcard into ram and the fact that the sdcard may even have been removed or swapped out the project needs to be saved into flash and the previously loaded samples can then just be kept in flash and used on boot (great idea for this from @democloid ).

**Comment by maks** [comment]
done as of #219

**Comment by maks** [comment]
Reopened issue as it was incorrectly closed when only the first part of the work was completed.

**Comment by iaalm** [comment]
Hi @maks , Checked #1408 . This looks like a good direction overall — the startup speed gain from skipping SD sample reload is very compelling.

I have one consistency concern for multi-card workflows:
- load project on card A (flash now has A sample layout)
- switch to card B and load (flash now has B layout)
- switch back to card A

In this case, card A may still have a valid /.current.samples (project/build id checks pass), but flash may no longer match that metadata.

Would you consider adding a flash-side signature block to bind SD metadata to current flash content?

Suggested lightweight approach:
- compute hash of /.current.samples
- store it in a small signature block at the end of sample flash region (with magic/version/build id)
- on restore, require both SD cache validation and flash signature match
- write signature as the final commit step after sample/cache write

This should keep the fast path, while making A/B card swaps much safer.
(Alternative strongest option is full-file CRC/hash, but I prefer this metadata-hash approach for lower startup cost.)

Happy to help implement if this approach makes sense.

**Comment by maks** [comment]
Thanks for looking at it. As I mentioned this was very much a rough first draft for implementing the feature and I had something similar in mind with using a hash of sample sizes (ie basically the offsets inside .current.samples) as this isn't just a concern for multicard use cases, the user can just as easily simply make direct changes to the samples in the current project. This wouldnt of course catch all potential issues for example multiple single cycle files could have their order or even files replaced and not be picked up by the offsets hash in this case but I think this is likely good enough given we should not be expecting to support users making changes to the current project outside the actual pT.

But I think I'd rather finish the work on this myself as I need to make time to test and review the PR whether you or I make the changes and it will be easier given I have already got the PR up. I'll make sure to update this issue once I have time to go back and add the hash check functionality.

**Comment by maks** [comment]
closing now as this is done and remaining aspects covered by other issues now
